version: '3.7'

services:
  server:
    build: .
    hostname: server
    container_name: Server
    networks:
      - default
  client1:
    build: .
    hostname: alice
    container_name: Alice
    networks:
      - default
  client2:
    build: .
    hostname: bob
    container_name: Bob
    networks:
      - default

networks:
  default:
    driver: bridge


