# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guessing_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guessing_game.proto',
  package='guessing_game',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13guessing_game.proto\x12\rguessing_game\"4\n\tGameState\"\'\n\x05state\x12\x0b\n\x07ongoing\x10\x00\x12\x07\n\x03won\x10\x01\x12\x08\n\x04over\x10\x02\"\x16\n\x05Guess\x12\r\n\x05guess\x18\x01 \x01(\x05\"\x18\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0c\n\x04\x66\x65\x65\x64\x18\x01 \x01(\t\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t2\x81\x01\n\x0cGuessingGame\x12\x38\n\x05reply\x12\x14.guessing_game.Guess\x1a\x17.guessing_game.Feedback\"\x00\x12\x37\n\ttell_name\x12\x13.guessing_game.Name\x1a\x13.guessing_game.Name\"\x00\x42\x02P\x01\x62\x06proto3'
)



_GAMESTATE_STATE = _descriptor.EnumDescriptor(
  name='state',
  full_name='guessing_game.GameState.state',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ongoing', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='won', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='over', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=90,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE_STATE)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='guessing_game.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMESTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=90,
)


_GUESS = _descriptor.Descriptor(
  name='Guess',
  full_name='guessing_game.Guess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guess', full_name='guessing_game.Guess.guess', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=114,
)


_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='guessing_game.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed', full_name='guessing_game.Feedback.feed', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=140,
)


_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='guessing_game.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='guessing_game.Name.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=162,
)

_GAMESTATE_STATE.containing_type = _GAMESTATE
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['Guess'] = _GUESS
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.message_types_by_name['Name'] = _NAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'guessing_game_pb2'
  # @@protoc_insertion_point(class_scope:guessing_game.GameState)
  })
_sym_db.RegisterMessage(GameState)

Guess = _reflection.GeneratedProtocolMessageType('Guess', (_message.Message,), {
  'DESCRIPTOR' : _GUESS,
  '__module__' : 'guessing_game_pb2'
  # @@protoc_insertion_point(class_scope:guessing_game.Guess)
  })
_sym_db.RegisterMessage(Guess)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'guessing_game_pb2'
  # @@protoc_insertion_point(class_scope:guessing_game.Feedback)
  })
_sym_db.RegisterMessage(Feedback)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'guessing_game_pb2'
  # @@protoc_insertion_point(class_scope:guessing_game.Name)
  })
_sym_db.RegisterMessage(Name)


DESCRIPTOR._options = None

_GUESSINGGAME = _descriptor.ServiceDescriptor(
  name='GuessingGame',
  full_name='guessing_game.GuessingGame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='reply',
    full_name='guessing_game.GuessingGame.reply',
    index=0,
    containing_service=None,
    input_type=_GUESS,
    output_type=_FEEDBACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='tell_name',
    full_name='guessing_game.GuessingGame.tell_name',
    index=1,
    containing_service=None,
    input_type=_NAME,
    output_type=_NAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GUESSINGGAME)

DESCRIPTOR.services_by_name['GuessingGame'] = _GUESSINGGAME

# @@protoc_insertion_point(module_scope)
